### ISSUE TITLE
GitHub authorization code not being saved to extension storage

### ISSUE THREAD

**Issue by lausan3** [AlgoArchiveExt/algoarchive.ext#8]
**Issue:** I found that when I sign in with GitHub, the extension doesn't save the authorization code it logs in the console.

Console after signing in with GitHub:
![image](https://github.com/user-attachments/assets/2da80b11-bfc7-4d0f-b873-683ed734c15f)

Which leads to the extension displaying a "GitHub Sign In" button instead of a repository button.

![image](https://github.com/user-attachments/assets/6be68d7e-db98-4934-8e18-9b54bc7c67c0)

**How to Reproduce:**
- Get a fresh install of the extension on main branch
- Build extension
- Load unpacked extension
- Try signing in with GitHub (First sign in will lead to correctly showing the GitHub Authorization page)
- Result: GitHub sign in button still displayed and re-opening the extension doesn't change it. The authorization code is not saved anywhere in the Extension Inspector.

**Comment by riimuru** [comment]
fixed as of https://github.com/AlgoArchiveExt/algoarchive.ext/commit/cd7e13f6afc59677dccbf88ad4bad2397c1f98ab!
